// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqfvx9tuH8nB6acXtRZ15cRcFtQSsj5NE',
    appId: '1:1000112839974:web:f88e8b16f9223deb9075e7',
    messagingSenderId: '1000112839974',
    projectId: 'pfaa-821cc',
    authDomain: 'pfaa-821cc.firebaseapp.com',
    storageBucket: 'pfaa-821cc.firebasestorage.app',
    measurementId: 'G-QHMLXC3YJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpUFdVAV6MTJQSfTuHrt0Nav70ddr5X-0',
    appId: '1:1000112839974:android:60a1f97298ae22f19075e7',
    messagingSenderId: '1000112839974',
    projectId: 'pfaa-821cc',
    storageBucket: 'pfaa-821cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVcZhm9x4Astz5e7ly1zrUSK4mhnI8uLw',
    appId: '1:1000112839974:ios:fb26c188ac9152bf9075e7',
    messagingSenderId: '1000112839974',
    projectId: 'pfaa-821cc',
    storageBucket: 'pfaa-821cc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVcZhm9x4Astz5e7ly1zrUSK4mhnI8uLw',
    appId: '1:1000112839974:ios:fb26c188ac9152bf9075e7',
    messagingSenderId: '1000112839974',
    projectId: 'pfaa-821cc',
    storageBucket: 'pfaa-821cc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqfvx9tuH8nB6acXtRZ15cRcFtQSsj5NE',
    appId: '1:1000112839974:web:0a9755ffb9fa021b9075e7',
    messagingSenderId: '1000112839974',
    projectId: 'pfaa-821cc',
    authDomain: 'pfaa-821cc.firebaseapp.com',
    storageBucket: 'pfaa-821cc.firebasestorage.app',
    measurementId: 'G-BTTNEZM7E4',
  );
}
